		<div class="navbar navbar-inverse">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<li class="active"><a href="./"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
					<?php require('./apps/loop_type.php'); ?>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Collections<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<?php require('./apps/loop_collection.php'); ?>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<?php require('./apps/cart.php'); ?>
					</li>
					<li>
						<a href="./?page=search"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search</button></a>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><?= $user->getNickname() ?></b> <span class="caret"></span></a>
						<ul id="login-dp" class="dropdown-menu">
							<li>
								<div class="row">
									<div class="col-md-12 text-center">
										<form method="POST" class="form" accept-charset="UTF-8">
											<div class="form-group">
												 <a href="">My orders</a>
											</div>
											<div class="form-group">
												 <a href="">My account</a>
											</div>
											<div class="form-group">
												 
											</div>
										</form>
									</div>
									<div class="bottom text-center">
										<form method="POST" class="form">
											<button name="action" value="disconnect" class="btn btn-danger btn-block">Disconnect</button>
										</form>
									</div>
							 	</div>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>