		<div class="navbar navbar-inverse">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<li class="active"><a href="./"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
					<?php require('./apps/loop_type.php'); ?>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Collections<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<?php require('./apps/loop_collection.php'); ?>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="./?page=search"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search</button></a>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
						<ul id="login-dp" class="dropdown-menu">
							<li>
								<div class="row">
									<div class="col-md-12">
										<form method="POST" class="form" accept-charset="UTF-8">
											<div class="form-group">
												 <label class="sr-only" for="nickname">Nickname</label>
												 <input type="text" class="form-control" name="nickname" placeholder="Nickname" required>
											</div>
											<div class="form-group">
												 <label class="sr-only" for="password">Password</label>
												 <input type="password" class="form-control" name="password" placeholder="Password" required>
											</div>
											<div class="form-group">
												 <button name="action" value="login" class="btn btn-primary btn-block">Sign in</button>
											</div>
										</form>
									</div>
									<div class="bottom text-center">
										New here ? <a href="./?page=register"><b>Join Us</b></a>
									</div>
							 	</div>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>