<div class="col-md-4">
	<article>
		<h3><a href="./weapon/<?= str_replace(' ', '-', $article->getWeapon()->getName()) ?>"><?= $article->getWeapon()->getName() ?></a> | <?= $article->getName() ?></h3>
		<a href="./rarity/<?= strtolower(str_replace(' ', '-',$article->getRarity()->getName())) ?>"><p class="raritycolor<?= $article->getIdRarity() ?>"><?= $article->getRarity()->getName()?> <?= $article->getType()->getNameS() ?></p></a>
		<a href="#<?= $article->getId()?>">
  			<img src="./public/img/skins/<?= $article->getId() ?>.png" alt="<?= $article->getWeapon()->getName()?> <?= $article->getName() ?>">
		</a>
		<a href="#" class="lightbox" id="<?= $article->getId()?>">
  			<img src="./public/img/skins/<?= $article->getId() ?>.png">
		</a>
		<span><?= $article->getPriceD()?></span>
		<a href="./collection/<?= strtolower(str_replace(' ', '-',$article->getCollection()->getName())) ?>" class="collection"><img src="./public/img/collections/<?= $article->getCollection()->getId() ?>.png" alt=""><p>Collection <?= $article->getCollection()->getName() ?></p></a>


		<button type="button" class="btn btn-info"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> More information</button>
		<form method="POST" class="form">
			<input type="hidden" class="form-control" name="id_skin" value="<?= $article->getId() ?>">
			<button name="cart" value="add" type="submit" class="btn btn-warning cart">Add to cart <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></button>
		</form>
	</article>
</div>