<div class="row centered-form">
	<div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Sign up for Skincsbenef <small>It's free!</small></h3>
			</div>
			<div class="panel-body">
				<form method="POST" class="form" accept-charset="UTF-8">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<input type="text" name="nickname" class="form-control input-sm" placeholder="Nickname" required>
							</div>
						</div>
					</div>
					<div class="form-group">
						<input type="email" name="mail" class="form-control input-sm" placeholder="Email Address" required>
					</div>
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6">
							<div class="form-group">
								<input type="password" name="password" class="form-control input-sm" placeholder="Password" required>
							</div>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6">
							<div class="form-group">
								<input type="password" name="password_confirmation" class="form-control input-sm" placeholder="Confirm Password" required>
							</div>
						</div>
					</div>
					<button name="action" value="register" class="btn btn-primary btn-block">Register</button>
				</form>
			</div>
		</div>
	</div>
</div>